from enum import Enum


class Currency(Enum):
    AED = "AED"
    ARS = "ARS"
    AUD = "AUD"
    BGN = "BGN"
    BHD = "BHD"
    BND = "BND"
    BRL = "BRL"
    BWP = "BWP"
    CAD = "CAD"
    CHF = "CHF"
    CLP = "CLP"
    CNY = "CNY"
    COP = "COP"
    CZK = "CZK"
    DKK = "DKK"
    EUR = "EUR"
    GBP = "GBP"
    HKD = "HKD"
    HRK = "HRK"
    HUF = "HUF"
    IDR = "IDR"
    ILS = "ILS"
    INR = "INR"
    IRR = "IRR"
    ISK = "ISK"
    JPY = "JPY"
    KRW = "KRW"
    KWD = "KWD"
    KZT = "KZT"
    LKR = "LKR"
    LYD = "LYD"
    MUR = "MUR"
    MXN = "MXN"
    MYR = "MYR"
    NOK = "NOK"
    NPR = "NPR"
    NZD = "NZD"
    OMR = "OMR"
    PHP = "PHP"
    PKR = "PKR"
    PLN = "PLN"
    QAR = "QAR"
    RON = "RON"
    RUB = "RUB"
    SAR = "SAR"
    SEK = "SEK"
    SGD = "SGD"
    THB = "THB"
    TRY = "TRY"
    TTD = "TTD"
    TWD = "TWD"
    USD = "USD"
    VEF = "VEF"
    ZAR = "ZAR"

    def __len__(self):
        return 3
